//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean TriggerPress;
        
        public Valve.VR.SteamVR_Action_Boolean TrackPadPress;
        
        public Valve.VR.SteamVR_Action_Boolean GripPress;
        
        public Valve.VR.SteamVR_Action_Boolean MenuPress;
        
        public Valve.VR.SteamVR_Action_Vector2 TrackPadPos;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
    }
}
