//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.default_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadPress
        {
            get
            {
                return SteamVR_Actions.default_TrackPadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripPress
        {
            get
            {
                return SteamVR_Actions.default_GripPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuPress
        {
            get
            {
                return SteamVR_Actions.default_MenuPress;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPadPos
        {
            get
            {
                return SteamVR_Actions.default_TrackPadPos;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
